# Generated by Django 4.1.7 on 2023-03-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('template', models.TextField(blank=True, verbose_name='Шаблон рассылки')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'активность',
                'verbose_name_plural': 'активности',
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Записей')),
                ('max_count', models.PositiveSmallIntegerField(default=1, verbose_name='Лимит записей')),
                ('is_group', models.BooleanField(default=False, verbose_name='Групповая?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('template', models.TextField(blank=True, verbose_name='Шаблон рассылки')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'консультация',
                'verbose_name_plural': 'консультации',
                'db_table': 'сonsultation',
            },
        ),
        migrations.CreateModel(
            name='ConsultationInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время конца')),
            ],
            options={
                'verbose_name': 'интервал консультаций',
                'verbose_name_plural': 'интервалы консультаций',
                'db_table': 'consult_interval',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='MessageToDelete',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('chat_id', models.PositiveBigIntegerField(verbose_name='Chat ID')),
                ('type', models.CharField(choices=[('imenu', 'Inline Menu'), ('rmenu', 'Reply Menu'), ('flood', 'Flood'), ('notif', 'Notification'), ('feedback', 'Feedback'), ('activity', 'Activity'), ('consultation', 'Consultation'), ('transfer', 'Transfer'), ('living', 'Living'), ('schedule', 'Schedule'), ('general', 'General')], max_length=12, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'отложенное удаление',
                'verbose_name_plural': 'отложенные удаления',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('date', models.DateField(verbose_name='Дата')),
                ('template', models.TextField(blank=True, verbose_name='Шаблон рассылки')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписание',
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('key', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, max_length=1024, null=True)),
                ('state', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'хранилище',
                'verbose_name_plural': 'хранилище',
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='TG ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('user', 'Участник'), ('listener', 'Слушатель'), ('expert', 'Эксперт'), ('manager', 'Организатор')], default='user', max_length=8, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'user',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('car_num', models.CharField(max_length=100, verbose_name='Номер машины')),
                ('driver_num', models.CharField(max_length=100, verbose_name='Номер водителя')),
                ('direction', models.CharField(choices=[('to', 'Туда'), ('from', 'Обратно')], default='to', max_length=4, verbose_name='Куда')),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'трансфер',
                'verbose_name_plural': 'трансфер',
                'db_table': 'transfer',
            },
        ),
        migrations.CreateModel(
            name='Living',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('room', models.CharField(max_length=100, verbose_name='Номер')),
                ('build', models.CharField(max_length=100, verbose_name='Корпус')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('send', 'Отправлено'), ('failed', 'Ошибка'), ('not_send', 'Не отправлено')], default='not_send', max_length=8, verbose_name='Статус рассылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'проживание',
                'verbose_name_plural': 'проживание',
                'db_table': 'living',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('impression', models.PositiveSmallIntegerField(verbose_name='Впечатление')),
                ('liked', models.PositiveSmallIntegerField(verbose_name='Понравился спикер')),
                ('useful', models.PositiveSmallIntegerField(verbose_name='Полезность')),
                ('relevant', models.PositiveSmallIntegerField(verbose_name='Применимость')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='pish.consultation', verbose_name='Консультация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'запись на консультацию',
                'verbose_name_plural': 'записи на консультации',
                'db_table': 'consult_records',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='expert',
            field=models.ForeignKey(limit_choices_to=models.Q(('status', 'expert')), on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='pish.consultationinterval', verbose_name='Интервал'),
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.activity', verbose_name='Активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pish.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'запись на активность',
                'verbose_name_plural': 'записи на активности',
                'db_table': 'activ_record',
            },
        ),
    ]
