# Generated by Django 4.1.7 on 2023-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_determination_map',
            field=models.URLField(default='', verbose_name='Карта самоопределения'),
            preserve_default=False,
        ),
    ]
