# Generated by Django 4.1.7 on 2023-06-12 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pish", "0003_alter_activityrecord_activity_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="consultation",
            table="consultation",
        ),
    ]
